# Development profile configuration

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/order_db}
    username: ${SPRING_DATASOURCE_USERNAME:order_user}
    password: ${SPRING_DATASOURCE_PASSWORD:dev_password_order}
  data:
    jdbc:
      repositories:
        enabled: true

logging:
  level:
    root: INFO
    com.ecommerce.order: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.kafka: DEBUG
    org.hibernate.SQL: DEBUG

app:
  payment:
    service:
      mock:
        success-rate: 1.0
        delay-ms: 500
