# Test profile configuration

spring:
  datasource:
    url: jdbc:tc:postgresql:15-alpine:///testdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 1

logging:
  level:
    root: WARN
    com.ecommerce.order: DEBUG
    org.testcontainers: INFO

management:
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    kafka:
      enabled: false

app:
  security:
    jwt:
      enabled: false
      mock-enabled: true
  payment:
    service:
      mock:
        success-rate: 1.0
        delay-ms: 10
  order:
    processing:
      idempotency-enabled: true

