# Test profile configuration

spring:
  datasource:
    url: jdbc:tc:postgresql:15-alpine:///testdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    listener:
      concurrency: 1

logging:
  level:
    root: WARN
    com.ecommerce.order: DEBUG
    org.testcontainers: INFO

app:
  payment:
    service:
      mock:
        success-rate: 1.0
        delay-ms: 10
  order:
    processing:
      idempotency-enabled: true

