# Test profile configuration

spring:
  datasource:
    url: jdbc:tc:postgresql:15-alpine:///testdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  data:
    jdbc:
      repositories:
        enabled: true

logging:
  level:
    root: WARN
    com.ecommerce.customer: DEBUG
    org.testcontainers: INFO

app:
  cart:
    ttl-minutes: 5
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
  security:
    jwt:
      enabled: false
      mock-enabled: true
