# Development profile configuration

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/customer_db}
    username: ${SPRING_DATASOURCE_USERNAME:customer_user}
    password: ${SPRING_DATASOURCE_PASSWORD:dev_password_customer}
  data:
    jdbc:
      repositories:
        enabled: true
    redis:
      password: dev_redis_password

logging:
  level:
    root: INFO
    com.ecommerce.customer: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

app:
  security:
    jwt:
      mock-enabled: true
